//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MelikeEryilmaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int ProductId { get; set; }
        public byte CategoryId { get; set; }
        public string ProductName { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual ProductDetails ProductDetails { get; set; }
    }
}
