//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frmMyCompanyDatabasewithEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personels
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personels()
        {
            this.Products = new HashSet<Products>();
        }
    
        public short Id { get; set; }
        public Nullable<byte> RoleId { get; set; }
        public string Name { get; set; }
        public string IdNo { get; set; }
        public string Address { get; set; }
        public string Mail { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsBoss { get; set; }
    
        public virtual Roles Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products> Products { get; set; }
    }
}
