//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frmMyCompanyDatabasewithEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public short Id { get; set; }
        public Nullable<short> PersonelId { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ProductDetails ProductDetails { get; set; }
        public virtual Personels Personels { get; set; }
    }
}
