//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SummerCampDatabaseExamples.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Denmedb2019Entities : DbContext
    {
        public Denmedb2019Entities()
            : base("name=Denmedb2019Entities")
        {
            Notifications = Set<Notifications>();
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        internal virtual DbSet<Notifications> Notifications { get; set; }
        public virtual DbSet<Faqs> Faqs { get; set; }
    }
}
