//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frmPixel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Educations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Educations()
        {
            this.EducationToStudents = new HashSet<EducationToStudents>();
            this.Personels = new HashSet<Personels>();
        }
    
        public byte EducationId { get; set; }
        public byte DepartmentId { get; set; }
        public string EducationName { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual Departments Departments { get; set; }
        public virtual EducationDetails EducationDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EducationToStudents> EducationToStudents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personels> Personels { get; set; }
    }
}
