//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frmPixel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationDetails
    {
        public byte EducationId { get; set; }
        public Nullable<short> HoursOfEducation { get; set; }
        public Nullable<double> Price { get; set; }
        public byte[] Description { get; set; }
        public Nullable<byte> EducationPeriod { get; set; }
    
        public virtual Educations Educations { get; set; }
    }
}
