//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frmPixel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int PaymentId { get; set; }
        public int StudentId { get; set; }
        public int CustomerId { get; set; }
        public byte[] PaymentName { get; set; }
        public Nullable<short> PaymentType { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Students Students { get; set; }
    }
}
