//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegTemp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public byte articleId { get; set; }
        public Nullable<byte> userId { get; set; }
        public string Description { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
